### ISSUE TITLE
Feature request: Telescope extension

### ISSUE THREAD

**Issue by lmburns** [chentoast/marks.nvim#71]
I like to use both the quickfix window and telescope. I think that it would be cool if there was some sort of telescope extension that could be packaged with this plugin

**Comment by chentoast** [comment]
Telescope integration would be cool, but should probably be implemented in a separate plugin. I’d rather not add and maintain support for another plugin that I don’t personally use

**Comment by lmburns** [comment]
Alright, I'll look into creating something like this. I know that telescope already has a marks picker builtin, but it is the same output of the `marks` command. I've already got something I've started on a while back that was integrating this plugin with telescope. For me to create it as a plugin and publish it apart from my dotfiles repository, I'll need to do a little bit more to it and add configuration options. 

The reason that I created this is because some other plugins (e.g., `folke/todo-comments.nvim`) provide both a quickfix and telescope version. I use both, but I understand. I'll close this and look into creating a plugin sometime fairly soon.

**Comment by chentoast** [comment]
I'm reopening this issue because ideally the plugin would expose bookmark information in a more easily accessible way rather than requiring any telescope extension to plumb through `require'marks'.bookmark_state`.

**Comment by insanum** [comment]
This works for me with bookmarks:

```
vim.keymap.set('n', '<leader>b', '<cmd>BookmarksListAll<CR><cmd>lcl<CR><cmd>Telescope loclist<CR>', { silent = true })
```

I see the new #106 pull request that integrates telescope. Curious how it's any different.

**Comment by ValJed** [comment]
Hi!
As stated by @chentoast I added methods allowing to simply return data from marks and bookmarks to be able to use it in the telescope plugin. (they could be useful for any new feature needing to get marks and bookmarks).

That's a nice workaround @insanum indeed. The advantage of the homemade telescope implementation is that we have to control over how infos are displayed in telescope.

For example, the telescope loclist display feels a bit messy to me:
![image](https://github.com/chentoast/marks.nvim/assets/17548370/97908634-4cff-4939-a7e0-b728eca2344a)

While mine looks like this for buffer marks (since I don't need to see in what file are these marks):
![image](https://github.com/chentoast/marks.nvim/assets/17548370/2546ce96-424d-43ea-8970-4fadd6e6e698)

And like this when looking for all project marks:
![image](https://github.com/chentoast/marks.nvim/assets/17548370/3fa1c710-22fb-402a-a4b8-b426019a2e71)

Moreover the file path will be showed based on user config.

Hope it makes sense.

**Comment by pidgeon777** [comment]
Hello, any update?

**Comment by Mulchman** [comment]
I've been able to use telescope to view marks with very little effort. In my existing `telescope.lua`, I do the following:
```
    local builtin = require("telescope.builtin")
   -- 
    vim.keymap.set("n", "<leader>fm", function()
      builtin.marks()
    end, { desc = "Telescope find marks" })
```

**Comment by ValJed** [comment]
@pidgeon777 as shared in my [PR](https://github.com/chentoast/marks.nvim/pull/106), you can use my fork until it's merged (if it's merged one day).
```
	{
		"ValJed/marks.nvim",
		branch = "feat-telescope-support-for-listing-marks",
                ...
         }
```
