### ISSUE TITLE
better support for global marks

### ISSUE THREAD

**Issue by qwertzui11** [chentoast/marks.nvim#75]
Hi

Thanks for this great plugin!

I was wandering if there is any support for toggling global marks?

`m;` toggles a buffer (lower case) mark. `Toggle the next available mark at the current line` 
I have not been able to find the same feature for global "upper case" marks.

With global marks I image a nice workflow in combination with Telescopes `builtin.marks` picker.

Thanks for your time,
Cheers,
Markus

**Comment by chentoast** [comment]
Instead of adding a toggle for capital marks, would it suffice to simply allow for deleting capital marks from a different buffer? That way, you can do `mA` and `dmA` from any buffer to toggle. This usecase seems uncommon enough that I'd like to avoid adding another mapping just to save on 2-3 keystrokes, plus it also runs a bit counter to what capital marks are intended for - long lasting associations to a location in a particular file. If you're looking to quickly save position across buffers, then you should probably be using bookmarks instead.

**Comment by qwertzui11** [comment]
You are correct, I miss interpreted the usage of marks. Bookmarks are the goal I was looking for.
